### ISSUE TITLE
Implement "Colloquial" Format for Numbers

### ISSUE THREAD

**Issue by garylzimmer** [zBritva/charticulator#16]
**Is your feature request related to a problem? Please describe.**
I deal with a lot of projects in the billions of USD in the USA and D3 uses SI prefixs, so G for Billions which is unfamiliar to a US business audience. I would like to see Charticular implement a custom format following this example:

https://github.com/d3/d3/issues/2241

**Comment by zBritva** [comment]
@garylzimmer The version with implementataion was deployed to https://ilfat-galiev.im/charticulator/ 
Works with "s" format, can be extended if it needs.

If you get a chance to check it out, would love some feedback. Thanks!
