### ISSUE TITLE
In Link window we can not choose link or band

### ISSUE THREAD

**Issue by MusicDendy** [zBritva/charticulator#29]
In Link window we can not choose link or band.
Can you fix it?

![image](https://github.com/zBritva/charticulator/assets/24212122/eae05985-83c4-4407-a04e-85b8fdf8ad56)

I have tested in Firefox and Edge.

**Comment by zBritva** [comment]
Deployed on https://ilfat-galiev.im/charticulator/ page. 
The fix will be included to next update of the visual too.

Pre relese is available in github repo:
https://github.com/zBritva/charticulator-visual-community/blob/master/docs/charticulatorVisualCommunity_VIEW.1.0.9.0.pbix
