### ISSUE TITLE
Boolean Mapping not taking effect in charticulator text element

### ISSUE THREAD

**Issue by SahilKothekar** [zBritva/charticulator#51]
When setting visibility of text element the values not the hide when we select No in Boolean mapping and also it does not show up when we select Yes . If we are selecting Yes then all the text visibility is gone

**Comment by zBritva** [comment]
The issues should be fixed in https://github.com/zBritva/charticulator/pull/42

**Comment by zBritva** [comment]
Fixed in [1.2.3.0](https://ilfat-galiev.im/docs/charticulator/changelog#1230-published-view)
